# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(default='0', max_length=1)),
                ('label_index', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('textfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('training_machine', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textify.User'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textify.User'),
        ),
        migrations.AddField(
            model_name='classificationmachine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textify.User'),
        ),
    ]
