# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(default='0', max_length=1)),
                ('label_index', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recognitionmachine',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='training_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classificationmachine',
            name='pickle',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='RecognitionMachine',
        ),
        migrations.AddField(
            model_name='drawing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textify.User'),
        ),
    ]
