# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='label',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='picture',
            name='label_index',
            field=models.IntegerField(default=0),
        ),
    ]
