# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textify', '0002_auto_20170304_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='background_task',
            name='verbose_name',
            field=models.TextField(null=True),
        ),
    ]
