# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textify', '0004_auto_20170228_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionmachine',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecognitionMachine',
        ),
    ]
